import { useState, useEffect, useCallback } from 'react';
import { api } from '../services/api';
import { formatMoney } from '../utils/formatMoney';

export const useSales = () => {
    const [sales, setSales] = useState([]);
    const [loading, setLoading] = useState(true);

    const loadSales = useCallback(async () => {
        setLoading(true);
        try {
            const salesData = await api.getSales();
            if (salesData.data) setSales(salesData.data);
        } catch (error) {
            console.error("Error loading sales:", error);
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        loadSales();
    }, [loadSales]);

    const createSale = useCallback(async (saleDetails) => {
        const { cartItems, total, paymentMethod, user, note } = saleDetails;

        const saleData = {
            // ID generated by backend
            date: new Date().toISOString(),
            items: cartItems,
            total: total,
            payment_method: paymentMethod,
            cashier: user?.name || "Unknown User",
            note: note
        };

        try {
            const result = await api.createSale(saleData);
            // Refrescar desde el servidor para que el reporte vea la venta al instante
            // (mismo shape: paymentMethod, items, status, etc.)
            await loadSales();
            return {
                success: true,
                result,
                saleData: {
                    id: result.saleId,
                    date: saleData.date,
                    items: cartItems,
                    total,
                    paymentMethod: paymentMethod,
                    cashier: saleData.cashier,
                    status: 'COMPLETED',
                    note
                }
            };
        } catch (error) {
            console.error("Error completing sale:", error);
            throw error;
        }
    }, [loadSales]);

    const processExchange = useCallback(async (exchangeDetails) => {
        const { returnedProduct, cartTotal, cartItems, user } = exchangeDetails;

        // 1. Update stock of returned product (+1)
        try {
            const updatedReturnedProduct = { ...returnedProduct, stock: returnedProduct.stock + 1 };
            await api.updateProduct(returnedProduct.id, updatedReturnedProduct);
        } catch (error) {
            console.error("Error updating returned product stock:", error);
            // We continue? Or fail? Best to fail if we can't update stock.
            throw new Error("Failed to return product to stock");
        }

        // 2. Create Sale Record
        const difference = cartTotal - returnedProduct.price;
        const note = `Cambio: Devolvió ${returnedProduct.name} (${formatMoney(returnedProduct.price)}). Diferencia: ${formatMoney(difference)}`;

        try {
            const result = await createSale({
                cartItems,
                total: cartTotal, // Record full value of new items? Or difference? App.jsx said "full value of new items"
                paymentMethod: 'EXCHANGE',
                user,
                note
            });
            return {
                ...result,
                difference,
                returnedProduct
            };
        } catch (error) {
            throw error;
        }
    }, [createSale]); // Added dependency createSale

    const voidSale = useCallback(async (saleId, reason) => {
        try {
            await api.voidSale(saleId, reason);
            // We could update local state manually, but refreshing from server is safer to get updated status and metadata
            await loadSales();
            return { success: true };
        } catch (error) {
            console.error("Error voiding sale:", error);
            throw error;
        }
    }, [loadSales]); // Added dependency loadSales

    return {
        sales,
        createSale,
        processExchange,
        voidSale,
        refreshSales: loadSales,
        loading
    };
};
